# Building on top of https://github.com/gmacario/easy-build

FROM gdpbuild/base

# Updating submodules
WORKDIR /home/build/genivi-dev-platform
RUN bash -c "source ./init.sh minnowboard"

CMD "/bin/bash"

# EOF
